#!/usr/bin/env bash
# Write a Bash script that displays listening TCP and UDP ports. 
# That only shows listening sockets. That shows the PID and name of the program to which each socket belongs.
netstat -tulpn
