#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an argument.
# Requirements: Accepts a string as an argument, Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed, Ping the IP 5 times
read -p "check network: " a
if [ "$a" == a ]; then
ping -c 5  "$a"
else
ping -c 5 8.8.8.8
fi
