#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an argument.
# Requirements: Accepts a string as an argument, Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed, Ping the IP 5 times
if [ $# -eq 0 ]; then
    echo "Usage: $0 8.8.8.8"
    exit 1
fi

ping -c 5 "$1"
