#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements: localhost resolves to 127.0.0.2 facebook.com resolves to 8.8.8.8.
sed -i 's/^127\.0\.0\.1\s*localhost/127.0.0.2    localhost/' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
