#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements: localhost resolves to 127.0.0.2 facebook.com resolves to 8.8.8.8.
sed -i '/127.0.0.1\s\+localhost/s/127.0.0.1/127.0.0.2/'
sed -i '/facebook.com/d' /etc/hosts
echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" > /etc/hosts
